// api/contact.js — Vercel serverless contact form handler
// Generated by Action Studio Factory — do not edit manually
// To update: run scripts/wire-contact.sh {slug} {email}

const RECIPIENT = process.env.CONTACT_RECIPIENT || "PLACEHOLDER_EMAIL";
const RESEND_API_KEY = process.env.RESEND_API_KEY;
const SLUG = "PLACEHOLDER_SLUG";

export default async function handler(req, res) {
  if (req.method !== "POST") {
    return res.status(405).json({ error: "Method not allowed" });
  }

  const { name, phone, email, service, address, message } = req.body;

  if (!name || !email) {
    return res.status(400).json({ error: "Name and email are required" });
  }

  if (!RESEND_API_KEY) {
    console.error("RESEND_API_KEY not set");
    return res.status(500).json({ error: "Email service not configured" });
  }

  try {
    const response = await fetch("https://api.resend.com/emails", {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${RESEND_API_KEY}`,
        "Content-Type": "application/json",
      },
      body: JSON.stringify({
        from: "Action Studio Factory <leads@actiondesignstudio.com>",
        to: [RECIPIENT],
        reply_to: email,
        subject: `New lead from ${name} — ${SLUG}`,
        html: `
          <h2>New lead from your website</h2>
          <table cellpadding="8" style="border-collapse:collapse;width:100%;max-width:600px">
            <tr><td style="background:#f5f5f5;font-weight:bold;width:140px">Name</td><td>${name}</td></tr>
            <tr><td style="background:#f5f5f5;font-weight:bold">Phone</td><td>${phone || "—"}</td></tr>
            <tr><td style="background:#f5f5f5;font-weight:bold">Email</td><td><a href="mailto:${email}">${email}</a></td></tr>
            <tr><td style="background:#f5f5f5;font-weight:bold">Service</td><td>${service || "—"}</td></tr>
            ${address ? `<tr><td style="background:#f5f5f5;font-weight:bold">Address</td><td>${address}</td></tr>` : ""}
            ${message ? `<tr><td style="background:#f5f5f5;font-weight:bold">Message</td><td>${message}</td></tr>` : ""}
          </table>
          <p style="color:#888;font-size:12px;margin-top:24px">
            Sent from ${SLUG}.actiondesignstudio.com via Action Studio Factory
          </p>
        `,
      }),
    });

    if (!response.ok) {
      const err = await response.json();
      console.error("Resend error:", err);
      return res.status(500).json({ error: "Failed to send email" });
    }

    // Redirect to thank-you or back with success param
    if (req.headers["content-type"]?.includes("application/x-www-form-urlencoded")) {
      return res.redirect(302, "/contact.html?sent=1");
    }
    return res.status(200).json({ ok: true });
  } catch (err) {
    console.error("Contact handler error:", err);
    return res.status(500).json({ error: "Server error" });
  }
}
